baseurl = "/"
languageCode = "en-us"
theme = "LoveIt"
paginate = 6
disqusShortname = "starptech"
googleAnalytics = "UA-115030952-1"
preserveTaxonomyNames = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[markup.goldmark.renderer]
  unsafe= true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    languageName = "English"
    title = "Dustin Deus - My personal blog"
    subtitle = "Dustin Deus - My personal blog"
    keywords = "blog, dustin deus, starptech, software engineer"
    copyright = "Dustin Deus"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "From Ã˜ to Hero, Web and Distributed Systems."
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/starptech"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About me"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/dustindeus"
      [[languages.en.menu.main]]
        identifier = "xing"
        name = "Xing"
        url = "https://www.xing.com/profile/Dustin_Deus2"
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/dustin-deus-a300b7108"